spring:
  application:
    name: oauth2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${yml.file.datasource.url}
    username: ${yml.file.datasource.username}
    password: ${yml.file.datasource.password}

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
